local WEAPONS = {
	AK47 = {
		name = "AK-47",
		model = "NanosWorld::SK_AK47",
		collision = 0,
		gravityEnabled = true,
		ammoInClip = 30,
		ammoInBag = 1000,
		clipCapacity = 30,
		baseDamage = 30,
		spread = 20,
		bulletCount = 1,
		ammoToReload = 30,
		maxBulletDistance = 20000,
		bulletSpeed = 15000,
		bulletColor = Color(20, 10000, 0),
		sightFovMultiplier = 0.5,
		sightLocation = Vector(0, 0, -14.85),
		sightRotation = Rotator(-1, 0, 0),
		leftHandLocation = Vector(26, 0, 8.5),
		leftHandRotation = Rotator(0, 60, 90),
		rightHandOffset = Vector(-10, 0, 0),
		handlingMode = 1,
		cadence = 0.15,
		canHoldUse = true,
		needToReleaseToFire = false,
		bulletTrailParticle = "NanosWorld::P_Bullet_Trail",
		barrelParticle = "NanosWorld::P_Weapon_BarrelSmoke",
		shellsParticle = "NanosWorld::P_Weapon_Shells_762x39",
		drySound = "NanosWorld::A_Rifle_Dry",
		loadSound = "NanosWorld::A_Rifle_Load",
		unloadSound = "NanosWorld::A_Rifle_Unload",
		zoomingSound = "NanosWorld::A_AimZoom",
		aimingSound = "NanosWorld::A_Rattle",
		shotSound = "NanosWorld::A_AK47_Shot",
		reloadingAnimation = "NanosWorld::AM_Mannequin_Reload_Rifle",
		aimingAnimation = "NanosWorld::AM_Mannequin_Sight_Fire",
		magazineMesh = "NanosWorld::SM_AK47_Mag_Empty"
	},
	AK74U = {
		name = "AK-74U",
		model = "NanosWorld::SK_AK74U",
		collision = 0,
		gravityEnabled = true,
		ammoInClip = 30,
		ammoInBag = 1000,
		clipCapacity = 30,
		baseDamage = 25,
		spread = 15,
		bulletCount = 1,
		ammoToReload = 30,
		maxBulletDistance = 20000,
		bulletSpeed = 15000,
		bulletColor = Color(10000, 20, 0),
		sightFovMultiplier = 0.5,
		sightLocation = Vector(0, 0, -16),
		sightRotation = Rotator(-3, 0, 0),
		leftHandLocation = Vector(26, 0, 8.5),
		leftHandRotation = Rotator(0, 60, 90),
		rightHandOffset = Vector(-10, 0, 0),
		handlingMode = 1,
		cadence = 0.15,
		canHoldUse = true,
		needToReleaseToFire = false,
		bulletTrailParticle = "NanosWorld::P_Bullet_Trail",
		barrelParticle = "NanosWorld::P_Weapon_BarrelSmoke",
		shellsParticle = "NanosWorld::P_Weapon_Shells_545x39",
		drySound = "NanosWorld::A_Rifle_Dry",
		loadSound = "NanosWorld::A_Rifle_Load",
		unloadSound = "NanosWorld::A_Rifle_Unload",
		zoomingSound = "NanosWorld::A_AimZoom",
		aimingSound = "NanosWorld::A_Rattle",
		shotSound = "NanosWorld::A_AK47_Shot",
		reloadingAnimation = "NanosWorld::AM_Mannequin_Reload_Rifle",
		aimingAnimation = "NanosWorld::AM_Mannequin_Sight_Fire",
		magazineMesh = "NanosWorld::SM_AK74U_Mag_Empty"
	},
	GE36 = {
		name = "GE36",
		model = "NanosWorld::SK_GE36",
		collision = 0,
		gravityEnabled = true,
		ammoInClip = 30,
		ammoInBag = 1000,
		clipCapacity = 30,
		baseDamage = 30,
		spread = 15,
		bulletCount = 1,
		ammoToReload = 30,
		maxBulletDistance = 20000,
		bulletSpeed = 15000,
		bulletColor = Color(10000, 20, 0),
		sightFovMultiplier = 0.5,
		sightLocation = Vector(0, 0, -16.6),
		sightRotation = Rotator(),
		leftHandLocation = Vector(25, 0, 10),
		leftHandRotation = Rotator(0, 60, 90),
		rightHandOffset = Vector(-10, 0, 0),
		handlingMode = 1,
		cadence = 0.1,
		canHoldUse = true,
		needToReleaseToFire = false,
		bulletTrailParticle = "NanosWorld::P_Bullet_Trail",
		barrelParticle = "NanosWorld::P_Weapon_BarrelSmoke",
		shellsParticle = "NanosWorld::P_Weapon_Shells_556x45",
		drySound = "NanosWorld::A_Rifle_Dry",
		loadSound = "NanosWorld::A_Rifle_Load",
		unloadSound = "NanosWorld::A_Rifle_Unload",
		zoomingSound = "NanosWorld::A_AimZoom",
		aimingSound = "NanosWorld::A_Rattle",
		shotSound = "NanosWorld::A_Rifle_Shot",
		reloadingAnimation = "NanosWorld::AM_Mannequin_Reload_Rifle",
		aimingAnimation = "NanosWorld::AM_Mannequin_Sight_Fire",
		magazineMesh = "NanosWorld::SM_GE36_Mag_Empty"
	},
	Glock = {
		name = "Glock",
		model = "NanosWorld::SK_Glock",
		collision = 0,
		gravityEnabled = true,
		ammoInClip = 17,
		ammoInBag = 1000,
		clipCapacity = 17,
		baseDamage = 15,
		spread = 20,
		bulletCount = 1,
		ammoToReload = 17,
		maxBulletDistance = 20000,
		bulletSpeed = 15000,
		bulletColor = Color(20, 10000, 0),
		sightFovMultiplier = 0.6,
		sightLocation = Vector(0, 0, -8.5),
		sightRotation = Rotator(-0.5, 0, 0),
		leftHandLocation = Vector(2, -1.5, 0),
		leftHandRotation = Rotator(0, 50, 130),
		rightHandOffset = Vector(-30, 0, 5),
		handlingMode = 0,
		cadence = 0.2,
		canHoldUse = false,
		needToReleaseToFire = false,
		bulletTrailParticle = "NanosWorld::P_Bullet_Trail",
		barrelParticle = "NanosWorld::P_Weapon_BarrelSmoke",
		shellsParticle = "NanosWorld::P_Weapon_Shells_9mm",
		drySound = "NanosWorld::A_Pistol_Dry",
		loadSound = "NanosWorld::A_Pistol_Load",
		unloadSound = "NanosWorld::A_Pistol_Unload",
		zoomingSound = "NanosWorld::A_AimZoom",
		aimingSound = "NanosWorld::A_Rattle",
		shotSound = "NanosWorld::A_Glock_Shot",
		reloadingAnimation = "NanosWorld::AM_Mannequin_Reload_Pistol",
		aimingAnimation = "NanosWorld::AM_Mannequin_Sight_Fire",
		magazineMesh = "NanosWorld::SM_Glock_Mag_Empty"
	},
	DesertEagle = {
		name = "Desert Eagle",
		model = "NanosWorld::SK_DesertEagle",
		collision = 0,
		gravityEnabled = true,
		ammoInClip = 7,
		ammoInBag = 1000,
		clipCapacity = 7,
		baseDamage = 45,
		spread = 65,
		bulletCount = 1,
		ammoToReload = 7,
		maxBulletDistance = 20000,
		bulletSpeed = 15000,
		bulletColor = Color(20, 10000, 0),
		sightFovMultiplier = 0.6,
		sightLocation = Vector(0, 0, -11.5),
		sightRotation = Rotator(-0.6, 0, 0),
		leftHandLocation = Vector(2, -1.5, 0),
		leftHandRotation = Rotator(0, 50, 130),
		rightHandOffset = Vector(-30, 0, 5),
		handlingMode = 0,
		cadence = 0.45,
		canHoldUse = false,
		needToReleaseToFire = false,
		bulletTrailParticle = "NanosWorld::P_Bullet_Trail",
		barrelParticle = "NanosWorld::P_Weapon_BarrelSmoke",
		shellsParticle = "NanosWorld::P_Weapon_Shells_45ap",
		drySound = "NanosWorld::A_Pistol_Dry",
		loadSound = "NanosWorld::A_Pistol_Load",
		unloadSound = "NanosWorld::A_Pistol_Unload",
		zoomingSound = "NanosWorld::A_AimZoom",
		aimingSound = "NanosWorld::A_Rattle",
		shotSound = "NanosWorld::A_DesertEagle_Shot",
		reloadingAnimation = "NanosWorld::AM_Mannequin_Reload_Pistol",
		aimingAnimation = "NanosWorld::AM_Mannequin_Sight_Fire",
		magazineMesh = "NanosWorld::SM_DesertEagle_Mag_Empty"
	},
	AR4 = {
		name = "AR4",
		model = "NanosWorld::SK_AR4",
		collision = 0,
		gravityEnabled = true,
		ammoInClip = 30,
		ammoInBag = 1000,
		clipCapacity = 30,
		baseDamage = 30,
		spread = 10,
		bulletCount = 1,
		ammoToReload = 30,
		maxBulletDistance = 20000,
		bulletSpeed = 15000,
		bulletColor = Color(10000, 20, 0),
		sightFovMultiplier = 0.5,
		sightLocation = Vector(0, 0, -17.6),
		sightRotation = Rotator(-0.2, 0, 0),
		leftHandLocation = Vector(25, 0, 10),
		leftHandRotation = Rotator(0, 60, 90),
		rightHandOffset = Vector(-12.5, 0, 0),
		handlingMode = 1,
		cadence = 0.1,
		canHoldUse = true,
		needToReleaseToFire = false,
		bulletTrailParticle = "NanosWorld::P_Bullet_Trail",
		barrelParticle = "NanosWorld::P_Weapon_BarrelSmoke",
		shellsParticle = "NanosWorld::P_Weapon_Shells_556x45",
		drySound = "NanosWorld::A_Pistol_Dry",
		loadSound = "NanosWorld::A_Pistol_Load",
		unloadSound = "NanosWorld::A_Pistol_Unload",
		zoomingSound = "NanosWorld::A_AimZoom",
		aimingSound = "NanosWorld::A_Rattle",
		shotSound = "NanosWorld::A_M4A1_Shot",
		reloadingAnimation = "NanosWorld::AM_Mannequin_Reload_Pistol",
		aimingAnimation = "NanosWorld::AM_Mannequin_Sight_Fire",
		magazineMesh = "NanosWorld::SM_AR4_Mag_Empty"
	},
	Moss500 = {
		name = "Moss 500",
		model = "NanosWorld::SK_Moss500",
		collision = 0,
		gravityEnabled = true,
		ammoInClip = 6,
		ammoInBag = 1000,
		clipCapacity = 6,
		baseDamage = 20,
		spread = 70,
		bulletCount = 6,
		ammoToReload = 1,
		maxBulletDistance = 10000,
		bulletSpeed = 15000,
		bulletColor = Color(10000, 20, 0),
		sightFovMultiplier = 0.75,
		sightLocation = Vector(0, 0, -12.5),
		sightRotation = Rotator(-1, 0, 0),
		leftHandLocation = Vector(238, 2, 2.5),
		leftHandRotation = Rotator(-5, 0, -180),
		rightHandOffset = Vector(-5, 0, 0),
		handlingMode = 1,
		cadence = 1,
		canHoldUse = true,
		needToReleaseToFire = false,
		bulletTrailParticle = "",
		barrelParticle = "NanosWorld::P_Weapon_BarrelSmoke",
		shellsParticle = "NanosWorld::P_Weapon_Shells_12Gauge",
		drySound = "NanosWorld::A_Shotgun_Dry",
		loadSound = "NanosWorld::A_Shotgun_Load_Bullet",
		unloadSound = "",
		zoomingSound = "NanosWorld::A_AimZoom",
		aimingSound = "NanosWorld::A_Rattle",
		shotSound = "NanosWorld::A_Shotgun_Shot",
		reloadingAnimation = "NanosWorld::AM_Mannequin_Reload_Shotgun",
		aimingAnimation = "NanosWorld::AM_Mannequin_Sight_Fire_Heavy",
		magazineMesh = ""
	},
	AP5 = {
		name = "AP5",
		model = "NanosWorld::SK_AP5",
		collision = 0,
		gravityEnabled = true,
		ammoInClip = 30,
		ammoInBag = 1000,
		clipCapacity = 30,
		baseDamage = 10,
		spread = 30,
		bulletCount = 1,
		ammoToReload = 30,
		maxBulletDistance = 20000,
		bulletSpeed = 15000,
		bulletColor = Color(10000, 20, 0),
		sightFovMultiplier = 0.5,
		sightLocation = Vector(0, 0, -16.5),
		sightRotation = Rotator(-2, 0, 0),
		leftHandLocation = Vector(24, 0, 9),
		leftHandRotation = Rotator(0, 60, 90),
		rightHandOffset = Vector(-15, 0, 0),
		handlingMode = 1,
		cadence = 0.1,
		canHoldUse = true,
		needToReleaseToFire = false,
		bulletTrailParticle = "NanosWorld::P_Bullet_Trail",
		barrelParticle = "NanosWorld::P_Weapon_BarrelSmoke",
		shellsParticle = "NanosWorld::P_Weapon_Shells_9x18",
		drySound = "NanosWorld::A_SMG_Dry",
		loadSound = "NanosWorld::A_SMG_Load",
		unloadSound = "NanosWorld::A_SMG_Unload",
		zoomingSound = "NanosWorld::A_AimZoom",
		aimingSound = "NanosWorld::A_Rattle",
		shotSound = "NanosWorld::A_LightMachine_Shot",
		reloadingAnimation = "NanosWorld::AM_Mannequin_Reload_Rifle",
		aimingAnimation = "NanosWorld::AM_Mannequin_Sight_Fire",
		magazineMesh = "NanosWorld::SM_AP5_Mag_Empty"
	},
	SMG11 = {
		name = "SMG11",
		model = "NanosWorld::SK_SMG11",
		collision = 0,
		gravityEnabled = true,
		ammoInClip = 32,
		ammoInBag = 1000,
		clipCapacity = 32,
		baseDamage = 15,
		spread = 35,
		bulletCount = 1,
		ammoToReload = 32,
		maxBulletDistance = 20000,
		bulletSpeed = 15000,
		bulletColor = Color(10000, 20, 0),
		sightFovMultiplier = 0.55,
		sightLocation = Vector(0, 0, -14.75),
		sightRotation = Rotator(-6.43, 0, 0),
		leftHandLocation = Vector(-3, 0, 0),
		leftHandRotation = Rotator(0, 25, 157.5),
		rightHandOffset = Vector(-35, 0, 0),
		handlingMode = 0,
		cadence = 0.1,
		canHoldUse = true,
		needToReleaseToFire = false,
		bulletTrailParticle = "NanosWorld::P_Bullet_Trail",
		barrelParticle = "NanosWorld::P_Weapon_BarrelSmoke",
		shellsParticle = "NanosWorld::P_Weapon_Shells_9x18",
		drySound = "NanosWorld::A_SMG_Dry",
		loadSound = "NanosWorld::A_SMG_Load",
		unloadSound = "NanosWorld::A_SMG_Unload",
		zoomingSound = "NanosWorld::A_AimZoom",
		aimingSound = "NanosWorld::A_Rattle",
		shotSound = "NanosWorld::A_LightMachine_Shot",
		reloadingAnimation = "NanosWorld::AM_Mannequin_Reload_Rifle",
		aimingAnimation = "NanosWorld::AM_Mannequin_Sight_Fire",
		magazineMesh = "NanosWorld::SM_AP5_Mag_Empty"
	}
}

local function createWeapon(location, rotation, weaponData)
	local weapon = NanosWeapon(location, rotation, weaponData.model, weaponData.collision, weaponData.gravityEnabled, weaponData.ammoInClip, weaponData.ammoInBag, weaponData.clipCapacity, weaponData.baseDamage, weaponData.spread, weaponData.bulletCount, weaponData.ammoToReload, weaponData.maxBulletDistance, weaponData.bulletSpeed, weaponData.bulletColor, weaponData.sightFovMultiplier, weaponData.sightLocation, weaponData.sightRotation, weaponData.leftHandLocation, weaponData.leftHandRotation, weaponData.rightHandOffset, weaponData.handlingMode, weaponData.cadence, weaponData.canHoldUse, weaponData.needToReleaseToFire, weaponData.bulletTrailParticle, weaponData.barrelParticle, weaponData.shellsParticle, weaponData.drySound, weaponData.loadSound, weaponData.unloadSound, weaponData.zoomingSound, weaponData.aimingSound, weaponData.shotSound, weaponData.reloadingAnimation, weaponData.aimingAnimation, weaponData.magazineMesh)
	enew(weapon, Weapon, weaponData.name)
	return weapon
end

NanosWorldWeapons = {
	AK47 = function(location, rotation)
		return createWeapon(location, rotation, WEAPONS.AK47)
	end,

	AK74U = function(location, rotation)
		return createWeapon(location, rotation, WEAPONS.AK74U)
	end,

	GE36 = function(location, rotation)
		return createWeapon(location, rotation, WEAPONS.GE36)
	end,

	Glock = function(location, rotation)
		return createWeapon(location, rotation, WEAPONS.Glock)
	end,

	DesertEagle = function(location, rotation)
		return createWeapon(location, rotation, WEAPONS.DesertEagle)
	end,

	AR4 = function(location, rotation)
		return createWeapon(location, rotation, WEAPONS.AR4)
	end,

	Moss500 = function(location, rotation)
		return createWeapon(location, rotation, WEAPONS.Moss500)
	end,

	AP5 = function(location, rotation)
		return createWeapon(location, rotation, WEAPONS.AP5)
	end,

	SMG11 = function(location, rotation)
		return createWeapon(location, rotation, WEAPONS.SMG11)
	end
}
